from pathlib import Path
import unittest


class InDesignBridgeTests(unittest.TestCase):
    def test_script_validates_snapshot_and_preserves_release_traceability(self) -> None:
        script = (
            Path(__file__).resolve().parents[1] / "indesign/ImportPerfectCatalog.jsx"
        ).read_text(encoding="utf-8")
        self.assertIn("perfect-catalog.indesign-snapshot.v1", script)
        self.assertIn('snapshot.release.status !== "published"', script)
        self.assertIn('insertLabel("perfect_catalog_release_id"', script)
        self.assertIn('insertLabel("perfect_catalog_snapshot_sha256"', script)
        self.assertIn("card.overflows", script)
        self.assertIn("SaveOptions.NO", script)
        for profile in ("T4", "T2", "T1", "TABLE"):
            self.assertIn(f'profile === "{profile}"' if profile != "T4" else 'return {perPage: 4', script)
        self.assertIn("separatorPage(document, groupLabel, theme)", script)
        self.assertIn("perfect-catalog.indesign-preflight.v1", script)
        self.assertIn("missing_images", script)
        self.assertIn("overflow_product_indexes", script)
        self.assertIn("unavailable_fonts", script)
        self.assertIn("imageBox.place(image)", script)
        self.assertIn('scriptFile.parent.fsName + "/catalog.indesign.json"', script)
        self.assertIn("adjacent.exists ? adjacent : File.openDialog", script)
        for theme in ("forest", "industrial", "midnight", "classic"):
            self.assertIn(f"{theme}:", script)
        self.assertIn('insertLabel("perfect_catalog_theme"', script)
        self.assertIn("themeDefinition(document, themeName, visual)", script)
        self.assertIn("visual.secondary_color", script)
        self.assertIn("function companyAccent", script)
        self.assertIn("visual.company.display_name", script)
        self.assertIn("Perfect Catalog Company Primary", script)
        self.assertIn("fillColor: theme.secondary", script)
        self.assertIn("fillColor: theme.paper", script)
        self.assertIn("strokeColor = theme.primary", script)
        self.assertIn("group_count", script)
        self.assertIn("page_count", script)
        self.assertIn('optionalValue(product, "brand")', script)
        self.assertIn('optionalValue(product, "oem_references")', script)
        self.assertIn("configureDocument(document)", script)
        self.assertIn('pageWidth = "210mm"', script)
        self.assertIn('pageHeight = "297mm"', script)
        self.assertIn("documentBleedUniformSize = true", script)
        self.assertIn('documentBleedTopOffset = "3mm"', script)
        self.assertIn("MeasurementUnits.POINTS", script)
        self.assertIn('insertLabel("perfect_catalog_page_format", "A4-portrait")', script)
        self.assertIn('visual.title_font_family', script)
        self.assertIn('visual.body_font_family', script)
        self.assertIn('fontByName(titleFamily, "Bold")', script)
        self.assertIn('fontByName(bodyFamily, "Regular")', script)
        self.assertIn('box.texts[0].appliedFont = selectedFont', script)
        self.assertIn("function vehicleMakeMark", script)
        self.assertIn('groupBy === "vehicle_make"', script)
        self.assertIn("visual.vehicle_makes", script)
        self.assertIn("function parseJson", script)
        self.assertIn("function stringifyJson", script)
        self.assertIn("El snapshot JSON contiene sintaxis no permitida", script)
        self.assertNotIn("no ofrece JSON.parse", script)
        self.assertIn("function adaptiveProfile", script)
        self.assertIn("score > 280", script)
        self.assertIn("score > 120", script)
        self.assertIn("var imageHeight = image ? definition.imageHeight : 0", script)
        self.assertIn("Fichas ampliadas automaticamente", script)
        self.assertIn('var SCRIPT_VERSION = "1.36.0"', script)
        self.assertIn('insertLabel("perfect_catalog_importer_version"', script)
        self.assertIn("function repairText", script)
        self.assertIn('"\\u00c2\\u00b7": "\\u00b7"', script)
        self.assertIn("function fitFrame", script)
        self.assertIn("fitFrame(heading, 30, 18, 1.15)", script)
        self.assertIn('if (groupBy === "vehicle_make") vehicleMakeMark', script)
        self.assertIn("visual, primaryGroup)", script)
        self.assertIn('groupLabel += "\\r" + secondaryGroup', script)
        self.assertIn("separatorPage(document, groupLabel, theme)", script)
        self.assertIn("function createContentsPages", script)
        self.assertIn("function fillContentsPages", script)
        self.assertIn("function addPageNumbers", script)
        self.assertIn("separator.documentOffset + 1", script)
        self.assertIn("function optionalValue", script)
        self.assertIn('if (oem) lines.push("OEM: " + oem)', script)
        self.assertIn('if (applications) lines.push("Aplicaciones: " + applications)', script)
        self.assertIn("card.paragraphs[1].fillColor = theme.primary", script)
        self.assertIn("Fuentes no disponibles", script)
        self.assertNotRegex(script, r"[^\x00-\x7F]")


if __name__ == "__main__":
    unittest.main()
